# Generated by Django 4.2.5 on 2023-11-08 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bithday',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 8, 9, 51, 11, 901751)),
        ),
    ]
