# Generated by Django 4.2.5 on 2023-11-22 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_students_slug_alter_students_bithday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='bithday',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 9, 27, 18, 451510)),
        ),
        migrations.AlterField(
            model_name='students',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
